language: rust
cache: cargo

os:
  - linux

rust:
  - stable
  - nightly

jobs:
  include:
    - rust: nightly
      before_install:
        - rustup component add llvm-tools-preview
        - cargo install grcov
        - cargo install rustfilt
        - cargo install cargo-binutils
      script:
        - ./profile.sh -e -t grcov -f lcov -o ./profile_test -- -f test_clippings.txt
        - ./profile.sh -t grcov -f lcov -o ./profile_run -- -f test_clippings.txt
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ./profile_test/lcov.info
        - bash <(curl -s https://codecov.io/bash) -f ./profile_run/lcov.info
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build
  - cargo run -- -h