language: rust
cache: cargo

os:
  - linux

rust:
  - stable
  - nightly

jobs:
  include:
    - rust: nightly
      before_install:
        - cargo install grcov
      script:
        - rustup component add llvm-tools-preview
        - ./profile.sh -t grcov -- -f test_clippings.txt
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build
  - cargo run -- -h