language: rust
cache: cargo

os:
  - linux

rust:
  - stable
  - nightly

jobs:
  include:
    - rust: nightly
      before_install:
        - rustup component add llvm-tools-preview
        - cargo install grcov
        - cargo install rustfilt
        - cargo install cargo-binutils
      script:
        - ./profile.sh -t cov -f text -- -f test_clippings.txt
      after_success:
        - ARRAY=($(find ./profile -type f -follow | tr ' ' '\n')); for i in "${ARRAY[@]}"; do bash <(curl -s https://codecov.io/bash) -f $i; done
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build
  - cargo run -- -h