version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: banucalin/clipping-parser-image:latest
    steps:
      - checkout
      - run: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-key-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: cargo-key-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/
  test:
    docker:
      - image: banucalin/clipping-parser-image:latest
    steps:
      - checkout
      - run: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-key-{{ checksum "Cargo.lock" }}
      - run: ./profile.sh -e -t grcov -f lcov -o ./profile_test
      - run: cargo test -- -Z unstable-options --format json --report-time | cargo2junit > unit_test_results.xml
      - store_test_results:
          path: unit_test_results.xml
      - store_artifacts:
          path: unit_test_results.xml

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          post-steps:
            - codecov/upload:
                file: ./profile_test/lcov.info