version: 2.1

jobs:
  build:
    docker:
      - image: banucalin/clipping-parser-image:latest
    steps:
      - checkout
      - run: cargo build --release
      - save_cache:
          key: cargo-key-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/
  test:
    docker:
      - image: banucalin/clipping-parser-image:latest
    steps:
      - checkout
      - run: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-key-{{ checksum "Cargo.lock" }}
      - run: cargo test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build